// ============================================
// BestWork - EN (İngilizce) Sözlük
// Anahtar: görünen Türkçe metin (kırpılmış) → İngilizce karşılık
// Eksik anahtar varsa orijinal Türkçe gösterilir (hiçbir şey kırılmaz).
// ============================================

export const en: Record<string, string> = {
  // ----- Ortak / genel -----
  'Hesabım': 'My Account',
  'Hesap': 'Account',
  'Siparişlerim': 'My Orders',
  'Adreslerim': 'My Addresses',
  'Cüzdanım': 'My Wallet',
  'Favorilerim': 'Favorites',
  'Sepet': 'Cart',
  'Sepetim': 'My Cart',
  'Giriş Yap': 'Sign In',
  'Çıkış Yap': 'Sign Out',
  'Ürün ara...': 'Search products...',
  'Tüm Kategoriler': 'All Categories',
  'Anasayfa': 'Home',
  'Kişisel': 'Personal',
  'Prim Yönetimi': 'Bonus Management',
  'İşlemlerim': 'My Transactions',
  'İletişim': 'Contact',
  'Üyelik Bilgilerim': 'My Membership',
  'Varis Bilgileri': 'Beneficiary Info',
  'Banka Bilgilerim': 'My Bank Accounts',
  'Sponsor Olduklarım': 'My Sponsored',
  'Başarı Raporu': 'Success Report',
  'Şifre Değiştir': 'Change Password',
  'Prim Detayları': 'Bonus Details',
  'Liderlik Primi': 'Leadership Bonus',
  'Binary Hareketleri': 'Binary Transactions',
  'Kariyer Takibi': 'Career Tracking',
  'Binary Ağacı': 'Binary Tree',
  'Referans ve Ekip Ağacı': 'Referral & Team Tree',
  'Yerleşim Bekleyenler': 'Pending Placements',
  'Alışveriş': 'Shopping',
  'EFT/HAVALE Bildirimleri': 'EFT / Wire Notifications',
  'Müşteri Kazancı': 'Retail Earnings',
  'İş Fırsatları': 'Opportunities',
  'Destek / İletişim': 'Support / Contact',
  'Kopyala': 'Copy',
  'Kopyalandı!': 'Copied!',
  'Kapat': 'Close',
  'Geri Dön': 'Go Back',
  'Ekle': 'Add',
  'Sil': 'Delete',
  'Kaydet': 'Save',
  'Düzenle': 'Edit',
  'Vazgeç': 'Cancel',
  'Aktif': 'Active',
  'Pasif': 'Inactive',
  'Bekliyor': 'Pending',
  'Ağaçta': 'Placed',
  'Sol Hat': 'Left Leg',
  'Sağ Hat': 'Right Leg',
  'Sol': 'Left',
  'Sağ': 'Right',
  'Tümü': 'All',
  'Tarih': 'Date',
  'Tutar': 'Amount',
  'Kazanç': 'Earnings',
  'Toplam': 'Total',
  'Kayıt': 'Record',
  'Ad Soyad': 'Full Name',
  'E-posta': 'E-mail',
  'Telefon': 'Phone',
  'Durum': 'Status',
  'Kayıt Tarihi': 'Registered',
  'Banka Adı': 'Bank Name',
  'Hesap Sahibi': 'Account Holder',
  'Yakınlık Derecesi': 'Relationship',
  'Dashboard': 'Dashboard',
  'Yeniden Dene': 'Retry',

  // ----- Üst menü / backoffice -----
  'Ünvan': 'Title',
  'Güncel Kariyeriniz': 'Current Career',
  'Seviyeniz': 'Your Level',
  'Ekibim': 'My Team',
  'Anlık Eşleşme': 'Instant Match',
  'Kişisel Toplam Kazanç': 'Total Personal Earnings',
  'Yerleşim Bekleyen': 'Awaiting Placement',
  'Anlık Kazanç': 'Instant Earnings',
  'Sistemdeki en yüksek kariyer unvanınız.': 'Your highest career title in the system.',
  'Bu ayki güncel kariyeriniz.': 'Your current career this month.',
  "Alışveriş PV'niz arttıkça paketiniz ve ürün indiriminiz otomatik yükselir.": "Your package and product discount rise automatically as your shopping PV grows.",
  'Doğrudan kaydettiğiniz 1. hat üyeleriniz.': 'First-line members you directly enrolled.',
  'Binary ağacınızdaki toplam üye sayısı.': 'Total members in your binary tree.',
  'Kısa kol ile eşleşen puanınız.': 'Points matched with your short leg.',
  'Sisteme katılımınızdan beri toplam kazancınız.': 'Your total earnings since joining.',
  'Ağaca yerleştirilmeyi bekleyen üyeler.': 'Members waiting to be placed in the tree.',
  'Bu cari dönemde oluşan güncel hakedişiniz.': 'Your earnings accrued in the current period.',
  'Üyelik seviyenizi yükseltmek için tıklayınız': 'Click to upgrade your membership level',
  'Yerleşim Bekleyen Üyeler': 'Members Awaiting Placement',
  'Paket Seviyenizi Yükseltin': 'Upgrade Your Package Level',
  'Sepete Git': 'Go to Cart',
  'Temizle': 'Clear',
  'Kalan:': 'Remaining:',
  'Üye No:': 'Member No:',
  'Rütbe:': 'Rank:',
  'Üye Kayıt Linkiniz': 'Your Registration Link',
  'Ağaca Yerleştir': 'Place in Tree',
  'Mevcut Seviye': 'Current Level',
  'GİRİŞİMCİ': 'ENTREPRENEUR',
  'Girişimci': 'Entrepreneur',
  'SOL HAT': 'LEFT LEG',
  'SAĞ HAT': 'RIGHT LEG',

  // ----- Anasayfa / mağaza -----
  'Öne Çıkan Kategoriler': 'Featured Categories',
  'Kategori bulunamadı': 'No categories found',
  'Alışverişe Başla': 'Start Shopping',
  'Ürünler': 'Products',
  'Tümünü Gör': 'View All',
  'Çok Satanlar': 'Best Sellers',
  'Trend Ürünler': 'Trending Products',
  'Yeni Eklenenler': 'New Arrivals',
  'En Çok Oy Alanlar': 'Top Rated',
  'Henüz ürün eklenmedi.': 'No products yet.',
  'Sepete Ekle': 'Add to Cart',
  'sepete eklendi': 'added to cart',
  'Kaçırma harika\nmarket fırsatlarını': 'Don\'t miss our great\nmarket deals',
  'Günlük bültene kaydolun': 'Sign up for the daily newsletter',
  'Taze Sebzeler\nBüyük İndirim': 'Fresh Vegetables\nBig Discount',
  'İlk siparişinizde %50 ye varan indirim': 'Up to 50% off your first order',
  'Her Gün Taze ve Temiz\nÜrünlerimizle': 'With our fresh and clean\nproducts every day',
  'Kahvaltını Sağlıklı\nve Kolay Yap': 'Make your breakfast\nhealthy and easy',
  'En İyi Organik\nÜrünler Online': 'Best organic products online',
  'Tüm Ürünler': 'All Products',
  'Ana Sayfa': 'Home',
  'Filtrele': 'Filter',
  'Kategori': 'Category',
  'Fiyat Aralığı (₺)': 'Price Range (₺)',
  'Min': 'Min',
  'Max': 'Max',
  'Sepetiniz boş': 'Your cart is empty',
  'Alışverişe başlamak için ürünleri keşfedin.': 'Explore products to start shopping.',
  'Hesap Oluştur': 'Create Account',
  'BestWork a katılın': 'Join BestWork',
  'Şifreler eşleşmiyor': 'Passwords do not match',
  'Şifre en az 6 karakter olmalı': 'Password must be at least 6 characters',
  'Kayıt başarılı!': 'Registration successful!',
  'Kayıt başarısız': 'Registration failed',
  'Kayıt Ol': 'Register',
  'Giriş': 'Login',
  'Şifre': 'Password',
  'Ad': 'First Name',
  'Soyad': 'Last Name',
  'Mesajınız': 'Your Message',
  'Kullanım Şartları': 'Terms of Use',
  'Gizlilik Politikası': 'Privacy Policy',

  // ----- Hesap / dashboard sayfaları -----
  'Hesap Bilgileri': 'Account Information',
  'Bakiye': 'Balance',
  'Toplam Kazanç': 'Total Earnings',
  'Yeni Varis': 'New Beneficiary',
  'Varis Ekle': 'Add Beneficiary',
  'Varislerim': 'My Beneficiaries',
  'Henüz varis eklemediniz.': 'You have not added any beneficiaries yet.',
  'Yeni Hesap Ekle': 'Add New Account',
  'Hesaplarım': 'My Accounts',
  'Henüz banka hesabı eklemediniz.': 'You have not added a bank account yet.',
  'Banka Hesabını Düzenle': 'Edit Bank Account',
  'Bildirimi Gönder': 'Submit Notification',
  'Dekont Görseli': 'Receipt Image',
  'Dekontu buraya sürükleyin veya seçin': 'Drag and drop or choose the receipt',
  'Yayına bağlanılamadı.': 'Unable to connect to the stream.',
  'Bağlantı geçici olarak kopmuş olabilir. Başka bir kanal seçin ya da yeniden deneyin.': 'The connection may have dropped. Try another channel or retry.',
  'Görüntülenen dönem': 'Displayed period',
  'Hareket': 'Transaction',
  'İşlem': 'Type',
  'Açıklama': 'Description',
  'Önceki': 'Previous',
  'Sonraki': 'Next',
  'kayıt': 'records',
  'hareket': 'transactions',
}
